title: Le Pata Negra
email: your-email@domain.com
description: >
    Blog sur le jambon pata negra ou le jambon ibérique, l'un des produits les plus célèbres de la gastronomie mondiale.
 Avec ce blog, nous souhaitons présenter tout ce qui concerne ce produit espagnol.
baseurl: "/"
url: http://keralahost.in/patanegra
google_adsense: Your-adsense-code

markdown: kramdown

name: Le Pata Negra
date: 2019-03-15 11:18:32 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/patanegra/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
    
author_image: 
    

author: patanegra
